### ISSUE TITLE
build flags

### ISSUE THREAD

**Issue by nkhdiscovery** [soham24/Opencv-android-SDK-3.3.1-with-opencl-and-contrib#1]
Hey, great job here!
I used this in my app but now I need to compile the whole repo myself from scratch - from opencv source.
Would you please provide the instructions?

**Comment by soham24** [comment]
Hello @nkhdiscovery 
Thanks for using this in your app. 
Opencv recently released 4.1.0 android SDK. and building it for Android is comparatively easy. 
It is provided in opencv docs. You should follow these official docs. 
Regards.
